name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deployer
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "."
        target: "/var/www/html/nathanszig"
